import Head from "next/head";
import Image from "next/image";
import { useContext } from "react";
import styles from "../../styles/Home.module.css";
import { AuthContext } from "../context/contexto";
import styled from "styled-components";
import Header from "../components/Header";
import Left from "../components/Left";
import Main from "../components/Main";

// export const Container = styled.div`
//   display: grid;
//   grid-template-columns: 100px 200px;
//   grid-template-rows: 80px calc(100vh - 80px);
//   grid-template-areas:
//     "header header"
//     "left main"
// `;

export const Container = styled.div`
  display: grid;
  grid-template-columns: 300px calc(100vw - 300px);
  grid-template-rows: 70px calc(100vh - 70px);
  grid-template-areas:
    "header header"
    "left main";
  overflow-x: hidden;
`;

export default function Home() {
  const { data } = useContext(AuthContext);

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Cards</title>
      </Head>

      <Header></Header>
      <Left></Left>
      <Main></Main>
    </Container>
  );
}
